TYPE_ANIMAL = 'A'
TYPE_PLANT = 'P'

SPREAD_RATE = 29

STRENGTH_PLANT = 0
INITIATIVE_PLANT = 0
 
STRENGTH_ANTELOPE = 4
INITIATIVE_ANTELOPE = 4
NAME_ANTELOPE = "ANTELOPE"
DRAW_ANTELOPE = 65

STRENGTH_BELLADONNA = 99
NAME_BELLADONNA = "BELLADONNA"
DRAW_BELLADONNA = 225

STRENGTH_CYBER_SHEEP = 11
INITIATIVE_CYBER_SHEEP = 4
NAME_CYBER_SHEEP = "CYBER SHEEP"
DRAW_CYBER_SHEEP = 234

STRENGTH_FOX = 3
INITIATIVE_FOX = 7
NAME_FOX = "FOX"
DRAW_FOX = 70

NAME_GRASS = "GRASS"
DRAW_GRASS = 193

NAME_GURANA = "GUARANA"
DRAW_GUARANA = 245

STRENGTH_HUMAN = 5
INITIATIVE_HUMAN = 4
NAME_HUMAN = "HUMAN"
DRAW_NORMAL_HUMAN = 104
DRAW_SUPER_HUMAN = 72
ABILITY_SET_STRENGTH = 10
ABILITY_COOLDOWN = 10
ABILITY_DURATION = 5
 
STRENGTH_SHEEP = 4
INITIATIVE_SHEEP = 4
NAME_SHEEP = "SHEEP"
DRAW_SHEEP = 83

STRENGTH_SOSNOWSKY = 10
NAME_SOSNOWSKY = "SOSNOWSKY"
DRAW_SOSNOWSKY = 197

NAME_SOW_THISTLE = "SOW_THISTLE"
DRAW_SOW_THISTLE = 207

STRENGTH_TURTLE = 2
INITIATIVE_TURTLE = 1
NAME_TURTLE = "TURTLE"
DRAW_TURTLE = 84

STRENGTH_WOLF = 9
INITIATIVE_WOLF = 5
NAME_WOLF = "WOLF"
DRAW_WOLF = 87